FROM python:3.7-alpine

WORKDIR /home

RUN apk update --no-cache
RUN apk upgrade --no-cache
RUN apk add --no-cache gcc g++ musl-dev bash
RUN pip install ryu networkx eventlet==0.30.2
COPY . /usr/local/lib/python3.7/site-packages/ryu/app

EXPOSE 8080 6653

ENTRYPOINT ["ryu-manager", "ryu.app.api_server"]
